services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - microservices-network
  microservice-data:
    build: ./microservices/microservice-data
    volumes:
      - ./microservices/microservice-data/src:/app/src
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/energyTradeSystem
    networks:
      - microservices-network

  microservice-trade:
    build: ./microservices/microservice-trade
    volumes:
      - ./microservices/microservice-trade/src:/app/src
    ports:
      - "3003:3003"
    networks:
      - microservices-network

  microservice-user:
    build: ./microservices/microservice-user
    volumes:
      - ./microservices/microservice-user/src:/app/src
    ports:
      - "3004:3004"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
